version: 0.2
            
phases:
  install:
    commands:
      - echo Installing grow
      - pip install keyring==12.2.0
      - pip install grow
  build:
    commands:
      - grow install
      - grow build
  post_build:
    commands:
      - aws s3 sync --delete build/ "s3://nd-website-demo"